### ISSUE TITLE
How do we use it?

### ISSUE THREAD

**Issue by mfmarlonferrari** [schurik77799/Poker-Objective-C#1]
Hi,
How do we used it? Install it? Compile it?
any doc?

**Comment by schurik77799** [comment]
Hello! It was my first experience in iOS development . 

How does it work?
You start server that is written on java on some PC (laptop) in local network!
(You should have JDK and JRE to compile and run it).

Than you should start iOS app on simulator or real device (it doesn't matter). 
In first view input you should enter ip address and port of server(which you set in java code).

To start game, you need at least two devices (simulators). Click "connect" and if all is "OK" you'll see second view. Here you can click play. (Here server will wait at least second gamer : max time limit proximately 3 minute). If 2 gamers clicked "Play" button to, you'll see play desk. And 
game started! 

Conclusion:
If you are starter in iOS dev. and you are interested in that project I can write more detailed documentation or help you in skype. I'll send you server code and give some advices.

Отправлено с iPad

**Comment by mfmarlonferrari** [comment]
Very thanks and keep the nice job!

**Comment by schurik77799** [comment]
This is server code. (Don't write code like this !)

2015-10-28 0:17 GMT+03:00 Marlon Ferrari <notifications@github.com>:
